// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAubqrzaspwB-Xi9te-CHgmv_KCiccZKRg',
    appId: '1:79600034667:web:c6602eae5995f97b0de22e',
    messagingSenderId: '79600034667',
    projectId: 'work-test-9e8b1',
    authDomain: 'work-test-9e8b1.firebaseapp.com',
    databaseURL: 'https://work-test-9e8b1-default-rtdb.firebaseio.com',
    storageBucket: 'work-test-9e8b1.appspot.com',
    measurementId: 'G-GN6JEDK8VE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz05HsQyTiY3uXMiYLr2uKn5kRIuSixqg',
    appId: '1:79600034667:android:3413697682623bc90de22e',
    messagingSenderId: '79600034667',
    projectId: 'work-test-9e8b1',
    databaseURL: 'https://work-test-9e8b1-default-rtdb.firebaseio.com',
    storageBucket: 'work-test-9e8b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8wwfCbrjhxmvH5y3zBtP7EBymXVsqsvw',
    appId: '1:79600034667:ios:fc083288b10a53d50de22e',
    messagingSenderId: '79600034667',
    projectId: 'work-test-9e8b1',
    databaseURL: 'https://work-test-9e8b1-default-rtdb.firebaseio.com',
    storageBucket: 'work-test-9e8b1.appspot.com',
    iosBundleId: 'com.example.workApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8wwfCbrjhxmvH5y3zBtP7EBymXVsqsvw',
    appId: '1:79600034667:ios:c4fb85f06a0625710de22e',
    messagingSenderId: '79600034667',
    projectId: 'work-test-9e8b1',
    databaseURL: 'https://work-test-9e8b1-default-rtdb.firebaseio.com',
    storageBucket: 'work-test-9e8b1.appspot.com',
    iosBundleId: 'com.example.workApp.RunnerTests',
  );
}
